"""updated like table

Revision ID: 2a2c72b477a4
Revises: aa3897ef9f51
Create Date: 2023-05-23 06:46:58.940974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a2c72b477a4'
down_revision = 'aa3897ef9f51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_column('like')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
